=== Thef1nansist/LP/OIT/XML/laba2/shiporder.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="UNIVERSITY">
    <xs:complexType>
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="SPECIALIZATION "> 
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "NAME" type="xs:string"/>
                        <xs:element name = "SET" type="xs:string"/>
                        <xs:element name = "SITY" type="xs:string"/>
                        <xs:element name = "EXAM" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Thef1nansist/LP/OIT/XML/laba2/laba2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="laba2.css"?>
<UNIVERSITY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='shiporder.xsd'>

    <SPECIALIZATION >
                <NAME >БГУИР</NAME>
                <SET >300 человек </SET>
                <SITY >Минск</SITY>
                <EXAM >369 баллов</EXAM>
    </SPECIALIZATION>

    <SPECIALIZATION >
                <NAME >БГТУ</NAME>
                <SET >200 человек </SET>
                <SITY >Минск</SITY>
                <EXAM >330 баллов</EXAM>
    </SPECIALIZATION>

    <SPECIALIZATION  >
                <NAME >БНТУ</NAME>
                <SET >320 человек  </SET>
                <SITY >Минск</SITY>
                <EXAM >334 балла</EXAM>
    </SPECIALIZATION>

    <SPECIALIZATION >
                <NAME >МИУ</NAME>
                <SET >180 человек  </SET>
                <SITY >Минск</SITY>
                <EXAM >310 баллов</EXAM>
    </SPECIALIZATION>

    <SPECIALIZATION >
                <NAME >ВГУ имени П. М. Машерова</NAME>
                <SET >140 человек  </SET>
                <SITY >Витебск</SITY>
                <EXAM >311 баллов</EXAM>
    </SPECIALIZATION>

    <SPECIALIZATION>
                <NAME >БрГТУ</NAME>
                <SET>120 человек  </SET>
                <SITY >Брест</SITY>
                <EXAM >315 баллов</EXAM>
    </SPECIALIZATION>

     <SPECIALIZATION>
                <NAME >ПГУ</NAME>
                <SET >100 человек </SET>
                <SITY >Полоцк</SITY>
                <EXAM >312 баллов</EXAM>
    </SPECIALIZATION>

</UNIVERSITY>
